/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ARAYUZ;

import KOD.IAnaFrameDon;



/**
 *
 * @author oguzh
 */
public class BashekimFrm extends javax.swing.JFrame implements IAnaFrameDon{
    
    

    /**
     * Creates new form BashekimFrm
     */
    public BashekimFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGeriGel = new javax.swing.JButton();
        btnHastaBilgileri = new javax.swing.JButton();
        btnPersonelBilgileri = new javax.swing.JButton();
        btnDoktorBilgileri = new javax.swing.JButton();
        btnIlacBilgileri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Başhekim Giriş Ekranı (admin yetkilendirildi)");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(235, 208, 235));

        btnGeriGel.setBackground(new java.awt.Color(94, 158, 255));
        btnGeriGel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGeriGel.setText("Geri");
        btnGeriGel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriGelActionPerformed(evt);
            }
        });

        btnHastaBilgileri.setBackground(new java.awt.Color(255, 238, 213));
        btnHastaBilgileri.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnHastaBilgileri.setText("Hasta Bilgilerine Eriş ve Düzenle");
        btnHastaBilgileri.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 183, 225), 3, true));
        btnHastaBilgileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHastaBilgileriActionPerformed(evt);
            }
        });

        btnPersonelBilgileri.setBackground(new java.awt.Color(255, 255, 222));
        btnPersonelBilgileri.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnPersonelBilgileri.setText("Personel Bilgilerine Eriş ve Düzenle");
        btnPersonelBilgileri.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 183, 255), 3, true));
        btnPersonelBilgileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonelBilgileriActionPerformed(evt);
            }
        });

        btnDoktorBilgileri.setBackground(new java.awt.Color(234, 255, 234));
        btnDoktorBilgileri.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnDoktorBilgileri.setText("Doktor Bilgilerine Eriş ve Düzenle");
        btnDoktorBilgileri.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 183, 255), 3, true));
        btnDoktorBilgileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoktorBilgileriActionPerformed(evt);
            }
        });

        btnIlacBilgileri.setBackground(new java.awt.Color(255, 224, 232));
        btnIlacBilgileri.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnIlacBilgileri.setText("İlaç Kayıtlarına Eriş ve Düzenle");
        btnIlacBilgileri.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 183, 255), 3, true));
        btnIlacBilgileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIlacBilgileriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGeriGel)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHastaBilgileri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPersonelBilgileri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoktorBilgileri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addComponent(btnIlacBilgileri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGeriGel)
                .addGap(33, 33, 33)
                .addComponent(btnHastaBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnDoktorBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnPersonelBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnIlacBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeriGelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriGelActionPerformed
        // TODO add your handling code here:
        btnAnaFrameDon(evt);
        
    }//GEN-LAST:event_btnGeriGelActionPerformed

    @Override
    public void btnAnaFrameDon(java.awt.event.ActionEvent evt){
          MainFrm mainfrm1 = new MainFrm();
       
        this.setVisible(false);
        mainfrm1.setVisible(true);
        mainfrm1.pack();
        mainfrm1.setLocationRelativeTo(null);
        
    }
    private void btnHastaBilgileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHastaBilgileriActionPerformed
        // TODO add your handling code here:
        BashekimhastaFrm bashekimhastaFrm1=new BashekimhastaFrm();
        this.setVisible(false);
        bashekimhastaFrm1.setVisible(true);
        bashekimhastaFrm1.pack();
        bashekimhastaFrm1.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnHastaBilgileriActionPerformed

    private void btnDoktorBilgileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoktorBilgileriActionPerformed
        // TODO add your handling code here:
        BashekimdoktorFrm bashekimdoktorFrm1=new BashekimdoktorFrm();
        this.setVisible(false);
        bashekimdoktorFrm1.setVisible(true);
        bashekimdoktorFrm1.pack();
        bashekimdoktorFrm1.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnDoktorBilgileriActionPerformed

    private void btnPersonelBilgileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonelBilgileriActionPerformed
        // TODO add your handling code here:
        BashekimpersonelFrm bashekimpersonelFrm1=new BashekimpersonelFrm();
        this.setVisible(false);
        bashekimpersonelFrm1.setVisible(true);
        bashekimpersonelFrm1.pack();
        bashekimpersonelFrm1.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnPersonelBilgileriActionPerformed

    private void btnIlacBilgileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIlacBilgileriActionPerformed
        // TODO add your handling code here:
        BashekimilacFrm bashekimilacFrm1=new BashekimilacFrm();
        this.setVisible(false);
        bashekimilacFrm1.setVisible(true);
        bashekimilacFrm1.pack();
        bashekimilacFrm1.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnIlacBilgileriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BashekimFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BashekimFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BashekimFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BashekimFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BashekimFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoktorBilgileri;
    private javax.swing.JButton btnGeriGel;
    private javax.swing.JButton btnHastaBilgileri;
    private javax.swing.JButton btnIlacBilgileri;
    private javax.swing.JButton btnPersonelBilgileri;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
