/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ARAYUZ;

import KOD.DbBaglanti;
import KOD.IAnaFrameDon;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import KOD.IKarsilaBilgidoldur;


/**
 *
 * @author oguzh
 */
public class DoktorgirisFrm extends javax.swing.JFrame implements IKarsilaBilgidoldur,IAnaFrameDon{
    static String secilenHastaTc;
    static String secilenIlacNo;
   
    

    /**
     * Creates new form DoktorgirisFrm
     */
    public DoktorgirisFrm() {
        initComponents();
        DbBaglanti.baglan();
        karsıla();
        hastacomboBoxListele();
        ilaccomboBoxListele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblKarsıla = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnGeriGel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnHastaGetir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblad = new javax.swing.JLabel();
        lblsoyad = new javax.swing.JLabel();
        lbltc = new javax.swing.JLabel();
        lbltel = new javax.swing.JLabel();
        lblcinsiyet = new javax.swing.JLabel();
        lblyas = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAsikayet = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArecete = new javax.swing.JTextArea();
        btnReceteGonder = new javax.swing.JButton();
        btnSikayetGonder = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblilacNo = new javax.swing.JLabel();
        lblilacAd = new javax.swing.JLabel();
        btnIlacGonder = new javax.swing.JButton();
        btnIlacGetir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doktor Giriş Ekranı");

        jPanel1.setBackground(new java.awt.Color(224, 255, 224));

        lblKarsıla.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblKarsıla.setText("Sayın DOKTOR Adı Soyadı Hoşgeldiniz!");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnGeriGel.setBackground(new java.awt.Color(94, 158, 255));
        btnGeriGel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGeriGel.setText("Geri");
        btnGeriGel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriGelActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Hasta Seçin");

        btnHastaGetir.setBackground(new java.awt.Color(255, 204, 51));
        btnHastaGetir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHastaGetir.setText("Hasta Getir");
        btnHastaGetir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHastaGetirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Hasta Tc :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Hasta Adı :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Hasta Soyadı :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Hasta Yaşı :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Hasta Telefonu :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Hasta Cinsiyet :");

        lblad.setText("bos");

        lblsoyad.setText("bos");

        lbltc.setText("bos");

        lbltel.setText("bos");

        lblcinsiyet.setText("bos");

        lblyas.setText("bos");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Reçete Gir");

        txtAsikayet.setColumns(20);
        txtAsikayet.setRows(5);
        jScrollPane1.setViewportView(txtAsikayet);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Şikayet Gir");

        txtArecete.setColumns(20);
        txtArecete.setRows(5);
        jScrollPane2.setViewportView(txtArecete);

        btnReceteGonder.setBackground(new java.awt.Color(102, 204, 255));
        btnReceteGonder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReceteGonder.setText("REÇETE GÖNDER");
        btnReceteGonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceteGonderActionPerformed(evt);
            }
        });

        btnSikayetGonder.setBackground(new java.awt.Color(176, 255, 255));
        btnSikayetGonder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSikayetGonder.setText("ŞİKAYET GÖNDER");
        btnSikayetGonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSikayetGonderActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("İlaç Seçin");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("İlaç No:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("İlaç İsmi:");

        lblilacNo.setText("bos");

        lblilacAd.setText("bos");

        btnIlacGonder.setBackground(new java.awt.Color(255, 158, 158));
        btnIlacGonder.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIlacGonder.setText("İLAÇ GÖNDER");
        btnIlacGonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIlacGonderActionPerformed(evt);
            }
        });

        btnIlacGetir.setBackground(new java.awt.Color(255, 158, 158));
        btnIlacGetir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIlacGetir.setText("İlaç Getir");
        btnIlacGetir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIlacGetirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblKarsıla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGeriGel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(42, 42, 42)
                                                        .addComponent(jLabel4))
                                                    .addComponent(jLabel6))
                                                .addComponent(jLabel7))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbltel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblcinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblyas, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(266, 266, 266))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(48, 48, 48)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblad, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(jLabel1)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lbltc, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(18, 18, 18))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel5)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(lblilacNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnHastaGetir, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblilacAd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnIlacGonder, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIlacGetir)
                                .addGap(29, 29, 29)))))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(btnSikayetGonder, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReceteGonder, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHastaGetir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblKarsıla, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGeriGel))
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(lbltc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIlacGetir)
                                .addGap(9, 9, 9))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblyas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lbltel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblcinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblilacNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lblilacAd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIlacGonder)
                        .addGap(49, 49, 49)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReceteGonder, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSikayetGonder, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeriGelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriGelActionPerformed
        btnAnaFrameDon(evt);
    }//GEN-LAST:event_btnGeriGelActionPerformed

     @Override
    public void btnAnaFrameDon(java.awt.event.ActionEvent evt){
          MainFrm mainfrm1 = new MainFrm();
       
        this.setVisible(false);
        mainfrm1.setVisible(true);
        mainfrm1.pack();
        mainfrm1.setLocationRelativeTo(null);
        
    }
    private void btnHastaGetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHastaGetirActionPerformed
        // TODO add your handling code here:
       
        String comboBoxYazısı;
        comboBoxYazısı = jComboBox1.getSelectedItem().toString();
        
        secilenHastaTc=comboBoxYazısı.substring(5, 16);
        
        bilgiDoldur();
        
        
        
        
        
    }//GEN-LAST:event_btnHastaGetirActionPerformed

    private void btnSikayetGonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSikayetGonderActionPerformed
        // TODO add your handling code here:
        
        if(txtAsikayet.toString().isEmpty()){
            JOptionPane.showMessageDialog(null,"Şikayet alanını boş bırakmayın!");
        }else{
            
            String UpdateSikayetSQL="UPDATE dislev SET sikayet = '"+txtAsikayet.getText().toString()+"' WHERE htc="+secilenHastaTc;
            
            DbBaglanti.update(UpdateSikayetSQL);
            
            JOptionPane.showMessageDialog(null,"Hastaya şikayet bilgisi eklendi, hasta bilgileri kendi ekranından takip edebilir!");
           
        }
        
        
    }//GEN-LAST:event_btnSikayetGonderActionPerformed

    private void btnReceteGonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceteGonderActionPerformed
        // TODO add your handling code here:
         if(txtArecete.toString().isEmpty()){
            JOptionPane.showMessageDialog(null,"Reçete alanını boş bırakmayın!");
        }else{
            
            String UpdateReceteSQL="UPDATE dislev SET recete = '"+txtArecete.getText().toString()+"' WHERE htc="+secilenHastaTc;
            
            DbBaglanti.update(UpdateReceteSQL);
            
            JOptionPane.showMessageDialog(null,"Hastaya reçete bilgisi eklendi, hasta bilgileri kendi ekranından takip edebilir!");
           
        }
    }//GEN-LAST:event_btnReceteGonderActionPerformed

    private void btnIlacGonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIlacGonderActionPerformed
        // TODO add your handling code here:
         if(lblilacAd.toString()=="bos"||lblilacNo.toString()=="bos"){
            JOptionPane.showMessageDialog(null,"Lütfen ilaç seçin!");
        }else{
            
            String UpdateSikayetSQL="UPDATE dislev SET ilacbilgisi = '"+lblilacAd.getText().toString()+"' WHERE htc="+secilenHastaTc;
            
            DbBaglanti.update(UpdateSikayetSQL);
            
            JOptionPane.showMessageDialog(null,"Hastaya ilaç bilgisi eklendi, hasta  kendi ekranından ilacını görebilir!");
           
        }
        
        
    }//GEN-LAST:event_btnIlacGonderActionPerformed

    private void btnIlacGetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIlacGetirActionPerformed
        // TODO add your handling code here:
        String comboBoxYazısı;
        comboBoxYazısı = jComboBox2.getSelectedItem().toString();
        
        secilenIlacNo=comboBoxYazısı.substring(10, 14);
        
        
        String secilenIlacGetirSQL="SELECT * FROM ilac WHERE ilacno='"+secilenIlacNo+"'";
    ResultSet myRs=DbBaglanti.listele(secilenIlacGetirSQL);
    
    
     try{
         
     while(myRs.next()){
        lblilacNo.setText(myRs.getString(1));
        lblilacAd.setText(myRs.getString(2));
        
         
        
     }
     }catch(SQLException e){
             e.printStackTrace();
             }
        
        
        
        
    }//GEN-LAST:event_btnIlacGetirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoktorgirisFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoktorgirisFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoktorgirisFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoktorgirisFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoktorgirisFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeriGel;
    private javax.swing.JButton btnHastaGetir;
    private javax.swing.JButton btnIlacGetir;
    private javax.swing.JButton btnIlacGonder;
    private javax.swing.JButton btnReceteGonder;
    private javax.swing.JButton btnSikayetGonder;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblKarsıla;
    private javax.swing.JLabel lblad;
    private javax.swing.JLabel lblcinsiyet;
    private javax.swing.JLabel lblilacAd;
    private javax.swing.JLabel lblilacNo;
    private javax.swing.JLabel lblsoyad;
    private javax.swing.JLabel lbltc;
    private javax.swing.JLabel lbltel;
    private javax.swing.JLabel lblyas;
    private javax.swing.JTextArea txtArecete;
    private javax.swing.JTextArea txtAsikayet;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void karsıla(){
        String girenDoktorTc=MainFrm.doktorTc;
        String karsilaSQL="SELECT * FROM doktor WHERE dtc='"+girenDoktorTc+"'";
        ResultSet myRs=DbBaglanti.listele(karsilaSQL);
        try{
        while(myRs.next()){
        lblKarsıla.setText("SAYIN DOKTOR "+myRs.getString(2)+" "+myRs.getString(3)+" HOŞGELDİNİZ");

 
    }}catch(SQLException e){
            e.printStackTrace();
            }
}

void hastacomboBoxListele(){
    String sql="SELECT * FROM hasta";
    ResultSet myRs=DbBaglanti.listele(sql);
    
  
    try{
        
        while(myRs.next()){
            jComboBox1.addItem("Tc:  "+myRs.getString(1)+" Adı:  "+myRs.getString(2)+" Soyadı:  "+myRs.getString(3));
        }
        
    }catch(SQLException e){
        e.printStackTrace();
    }
            
}
void ilaccomboBoxListele(){
    String sql="SELECT * FROM ilac";
    ResultSet myRs=DbBaglanti.listele(sql);
    
  
    try{
        
        while(myRs.next()){
            jComboBox2.addItem("İlaç no:  "+myRs.getString(1)+" İlaç ismi:  "+myRs.getString(2));
        }
        
    }catch(SQLException e){
        e.printStackTrace();
    }
            
}

@Override
public void bilgiDoldur(){
    
    String secilenHastaGetirSQL="SELECT * FROM hasta WHERE htc='"+secilenHastaTc+"'";
    ResultSet myRs=DbBaglanti.listele(secilenHastaGetirSQL);
    
    
     try{
         
     while(myRs.next()){
        lbltc.setText(myRs.getString(1));
        lblad.setText(myRs.getString(2));
        lblsoyad.setText(myRs.getString(3));
        lblyas.setText(myRs.getString(4));
        lbltel.setText(myRs.getString(5));
        lblcinsiyet.setText(myRs.getString(7));
        
         
        
     }
     }catch(SQLException e){
             e.printStackTrace();
             }
     
       
}


}
